"""Add bot status and user slots

Revision ID: ca147cad79d8
Revises: 720dbfcb5ffa
Create Date: 2026-06-22 16:10:44.544872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca147cad79d8'
down_revision: Union[str, Sequence[str], None] = '720dbfcb5ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    op.add_column('bots', sa.Column('users_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bots', sa.Column('is_token_locked', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('bots', 'bot_token_enc',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('bots', 'tg_bot_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('users', sa.Column('lifetime_slots', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lifetime_slots')
    op.alter_column('bots', 'tg_bot_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('bots', 'bot_token_enc',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('bots', 'is_token_locked')
    op.drop_column('bots', 'users_count')
    op.drop_column('bots', 'status')
    # ### end Alembic commands ###
