"""Add agreed_to_tos to lead

Revision ID: 720dbfcb5ffa
Revises: 
Create Date: 2026-06-17 13:07:41.865312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720dbfcb5ffa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'tg_bot_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('bots_tg_bot_id_key'), 'bots', type_='unique')
    op.create_index(op.f('ix_bots_tg_bot_id'), 'bots', ['tg_bot_id'], unique=True)
    
    # ⚡️ Добавляем колонку как Nullable сначала
    op.add_column('leads', sa.Column('agreed_to_tos', sa.Boolean(), nullable=True))
    
    # ⚡️ Проставляем дефолтное значение False для всех существующих строк
    op.execute("UPDATE leads SET agreed_to_tos = False")
    
    # ⚡️ Теперь делаем колонку NOT NULL
    op.alter_column('leads', 'agreed_to_tos', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'agreed_to_tos')
    op.drop_index(op.f('ix_bots_tg_bot_id'), table_name='bots')
    op.create_unique_constraint(op.f('bots_tg_bot_id_key'), 'bots', ['tg_bot_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('bots', 'tg_bot_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
